include:
  - project: 'colorifix/colorifixcab/ci-templates'
    ref: 'master'
    file: 'ci-build-server.yml'
  - project: 'colorifix/colorifixcab/ci-templates'
    ref: 'master'
    file: 'ci-deploy-server.yml'

stages:
  - build
  - release

variables:
  IMAGE_TAG: "registry.gitlab.com/$CI_PROJECT_PATH:v$RELEASE"
  # Extra argument to use with the release utility so it doesn't wait on test pipelines
  ARGS: "--no-pipeline"
  # Name of the docker-compose project
  PROJECT_NAME: "constelite"

# Override build job to also build images if there is a MR
build:
  before_script:
    - |
      if [ -z "$RELEASE" ]; then
        export IMAGE_TAG="registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG"
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $RELEASE' 
      when: always
    - when: never