site_name: Constelite
repo_url: https://gitlab.com/colorifix/constelite/constelite
repo_name: Colorifix/constelite
theme:
  name: material
  icon:
    repo: fontawesome/brands/gitlab
  logo: img/logo.png
  favicon: img/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
  palette:
    scheme: slate
    primary: blue grey
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - mkdocstrings
  - autorefs

site_dir: public

nav:
  - Welcome:
    - index.md
  - Getting started:
    - getting_started/index.md
    - User guide:
      - getting_started/user_guide/index.md
      - Calling protocols: getting_started/user_guide/calling_protocols.md
      - Working with Camunda API: getting_started/user_guide/camunda.md
      - Writing a converter protocol: getting_started/user_guide/converters.md
      - GraphQL queries: getting_started/user_guide/graphql.md
    - Key concepts:
      - getting_started/key_concepts/index.md
      - State Model: getting_started/key_concepts/state_model.md
      - Store: getting_started/key_concepts/store.md
      - Reference: getting_started/key_concepts/ref.md
      - Protocol: getting_started/key_concepts/protocol.md
      - API: getting_started/key_concepts/api.md
      - Hook: getting_started/key_concepts/hook.md
  - For Developers:
    - for_developers/index.md
    - GraphQL: for_developers/graphql.md
    - CamundaAPI: for_developers/camunda_api.md
    - API:
      - constelite:
        - models:
          - for_developers/API/constelite/models/state_model.md
        - store:
          - for_developers/API/constelite/models/store.md
